import "./globals.css";
import styles from "./page.module.css";
import  Providers from "./Providers";
import NavBar from "./NavBar"
import Footer from "./Footer"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
    <html lang="en">
      <body className={[styles.container, styles.body].join(" ")}>
      <Providers>
        <NavBar></NavBar>
        {children}
        <Footer className={styles.footer}></Footer>
      </Providers>
      </body>
    </html>
   
  );
}
